class Photo < ActiveRecord::Base
	belongs_to :user

	before_save { link.downcase! }

	VALID_LINK_REGEX = /\Ahttp:\/\/www.[a-z.]+[a-z]+\z/i
	validates :link, presence: true, format: { with: VALID_LINK_REGEX }
	validates :location_name, presence: true

	#converts name of country into location code readable by AmMaps
	def location_code
		case location_name
			when "United Arab Emirates"	then "AE"
			when "Afghanistan"	then "AF"
			when "Albania"	then "AL"
			when "Armenia"	then "AM"
			when "Angola"	then "AO"
			when "Argentina"	then "AR"
			when "Austria"	then "AT"
			when "Australia"	then "AU"
			when "Azerbaijan"	then "AZ"
			when "Bosnia and Herzegovina"	then "BA"
			when "Bangladesh"	then "BD"
			when "Belgium"	then "BE"
			when "Burkina Faso"	then "BF"
			when "Bulgaria"	then "BG"
			when "Burundi"	then "BI"
			when "Benin"	then "BJ"
			when "Brunei Darussalam"	then "BN"
			when "Bolivia"	then "BO"
			when "Brazil"	then "BR"
			when "Bahamas"	then "BS"
			when "Bhutan"	then "BT"
			when "Botswana"	then "BW"
			when "Belarus"	then "BY"
			when "Belize"	then "BZ"
			when "Canada"	then "CA"
			when "Democratic Republic of Congo"	then "CD"
			when "Central African Republic"	then "CF"
			when "Republic of Congo"	then "CG"
			when "Switzerland"	then "CH"
			when "Côte d'Ivoire"	then "CI"
			when "Chile"	then "CL"
			when "Cameroon"	then "CM"
			when "China"	then "CN"
			when "Colombia"	then "CO"
			when "Costa Rica"	then "CR"
			when "Cuba"	then "CU"
			when "Cyprus"	then "CY"
			when "Czech Republic"	then "CZ"
			when "Germany"	then "DE"
			when "Djibouti"	then "DJ"
			when "Denmark"	then "DK"
			when "Dominican Republic"	then "DO"
			when "Algeria"	then "DZ"
			when "Ecuador"	then "EC"
			when "Estonia"	then "EE"
			when "Egypt"	then "EG"
			when "Western Sahara"	then "EH"
			when "Eritrea"	then "ER"
			when "Spain"	then "ES"
			when "Ethiopia"	then "ET"
			when "Falkland Islands"	then "FK"
			when "Finland"	then "FI"
			when "Fiji"	then "FJ"
			when "France"	then "FR"
			when "Gabon"	then "GA"
			when "United Kingdom"	then "GB"
			when "Georgia"	then "GE"
			when "French Guiana"	then "GF"
			when "Ghana"	then "GH"
			when "Greenland"	then "GL"
			when "Gambia"	then "GM"
			when "Guinea"	then "GN"
			when "Equatorial Guinea"	then "GQ"
			when "Greece"	then "GR"
			when "Guatemala"	then "GT"
			when "Guinea-Bissau"	then "GW"
			when "Guyana"	then "GY"
			when "Honduras"	then "HN"
			when "Croatia"	then "HR"
			when "Haiti"	then "HT"
			when "Hungary"	then "HU"
			when "Indonesia"	then "ID"
			when "Ireland"	then "IE"
			when "Israel"	then "IL"
			when "India"	then "IN"
			when "Iraq"	then "IQ"
			when "Iran"	then "IR"
			when "Iceland"	then "IS"
			when "Italy"	then "IT"
			when "Jamaica"	then "JM"
			when "Jordan"	then "JO"
			when "Japan"	then "JP"
			when "Kenya"	then "KE"
			when "Kyrgyzstan"	then "KG"
			when "Cambodia"	then "KH"
			when "North Korea"	then "KP"
			when "South Korea"	then "KR"
			when "Kosovo"	then "XK"
			when "Kuwait"	then "KW"
			when "Kazakhstan"	then "KZ"
			when "Lao People's Democratic Republic"	then "LA"
			when "Lebanon"	then "LB"
			when "Sri Lanka"	then "LK"
			when "Liberia"	then "LR"
			when "Lesotho"	then "LS"
			when "Lithuania"	then "LT"
			when "Luxembourg"	then "LU"
			when "Latvia"	then "LV"
			when "Libya"	then "LY"
			when "Morocco"	then "MA"
			when "Moldova"	then "MD"
			when "Montenegro"	then "ME"
			when "Madagascar"	then "MG"
			when "Macedonia"	then "MK"
			when "Mali"	then "ML"
			when "Myanmar"	then "MM"
			when "Mongolia"	then "MN"
			when "Mauritania"	then "MR"
			when "Malawi"	then "MW"
			when "Mexico"	then "MX"
			when "Malaysia"	then "MY"
			when "Mozambique"	then "MZ"
			when "Namibia"	then "NA"
			when "New Caledonia"	then "NC"
			when "Niger"	then "NE"
			when "Nigeria"	then "NG"
			when "Nicaragua"	then "NI"
			when "Netherlands"	then "NL"
			when "Norway"	then "NO"
			when "Nepal"	then "NP"
			when "New Zealand"	then "NZ"
			when "Oman"	then "OM"
			when "Panama"	then "PA"
			when "Peru"	then "PE"
			when "Papua New Guinea"	then "PG"
			when "Philippines"	then "PH"
			when "Poland"	then "PL"
			when "Pakistan"	then "PK"
			when "Puerto Rico"	then "PR"
			when "Palestinian Territories"	then "PS"
			when "Portugal"	then "PT"
			when "Paraguay"	then "PY"
			when "Qatar"	then "QA"
			when "Romania"	then "RO"
			when "Serbia"	then "RS"
			when "Russia"	then "RU"
			when "Rwanda"	then "RW"
			when "Saudi Arabia"	then "SA"
			when "Solomon Islands"	then "SB"
			when "Sudan"	then "SD"
			when "Sweden"	then "SE"
			when "Slovenia"	then "SI"
			when "Svalbard and Jan Mayen"	then "SJ"
			when "Slovakia"	then "SK"
			when "Sierra Leone"	then "SL"
			when "Senegal"	then "SN"
			when "Somalia"	then "SO"
			when "Suriname"	then "SR"
			when "South Sudan"	then "SS"
			when "El Salvador"	then "SV"
			when "Syria"	then "SY"
			when "Swaziland"	then "SZ"
			when "Chad"	then "TD"
			when "French Southern and Antarctic Lands"	then "TF"
			when "Togo"	then "TG"
			when "Thailand"	then "TH"
			when "Tajikistan"	then "TJ"
			when "Timor-Leste"	then "TL"
			when "Turkmenistan"	then "TM"
			when "Tunisia"	then "TN"
			when "Turkey"	then "TR"
			when "Trinidad and Tobago"	then "TT"
			when "Taiwan"	then "TW"
			when "Tanzania"	then "TZ"
			when "Ukraine"	then "UA"
			when "Uganda"	then "UG"
			when "United States"	then "US"
			when "Uruguay"	then "UY"
			when "Uzbekistan"	then "UZ"
			when "Venezuela"	then "VE"
			when "Vietnam"	then "VN"
			when "Vanuatu"	then "VU"
			when "Yemen"	then "YE"
			when "South Africa"	then "ZA"
			when "Zambia"	then "ZM"
			when "Zimbabwe"	then "ZW"
			else
				"ERROR"
			end
	end
end
